---
# vars file for rbenv
dependencies:
  - gcc-c++ 
  - make
  - glibc-headers
  - openssl-devel
  - readline 
  - readline-devel 
  - libyaml-devel
  - zlib
  - zlib-devel
  - libxml2
  - libxml2-devel
  - libxslt
  - libxslt-devel
  - mysql-devel
  - ImageMagick # for rails app to show image
  - ImageMagick-devel
  

rbenv_url: "https://github.com/sstephenson/rbenv.git"
ruby_build_url: "https://github.com/rbenv/ruby-build.git"
ruby_version: "2.6.3"